### ISSUE TITLE
cls: Improve performance by reducing the size of data read from disk

### ISSUE THREAD

**Issue by carlosggarcia** [xC-ell/xCell#75]
One of the main bottle necks at this moment is the loading of the (cov)workspaces. We do not need all the information stored in them. We should only load what we actually need by accessing the corresponding part of the fits file.

**Comment by damonge** [comment]
This should help: https://github.com/LSSTDESC/NaMaster/pull/146.
I'll try to get it merged today and we can implement the changes that will make things faster in xCell

**Comment by carlosggarcia** [comment]
Results for DESY1wl, nside 4096, 24 cores and 189.6 GB of RAM

- Nothing already computed: 
  - Masks read. It took 2.55 min
  - Computed C_ells. It took 129.18 min
  - Out of memory

I will update this comment with the results of the others when available.

**Comment by damonge** [comment]
OK, let's see:
- "Computed C_ells" involves, among other things, reading workspaces so you can couple the fiducial C_ells. 
- "Read workspaces" involves just reading the mode-coupling matrices of the 2 C_ells whose covariance you're computing.
Correct?

**Comment by carlosggarcia** [comment]
Correct.

**Comment by damonge** [comment]
OK, so here's my proposal to save time on both of these:
1. When we compute the fiducial C_ells, we mode-couple them, and save the mode-coupled version. Thus, we only need to read that one instead of reading the uncoupled version and the full MCM. This still means we need to read the workspace, but only once for each C_ell, not 4 times for each covariance element.
2. I create a method in namaster that reads only the binned mode-coupling matrix, which is the one you need for covariances. This one is much smaller and should be much faster to read.

This should save us ~15min per covariance element, which is not negligible.
Then we should check if there's a way to accelerate the Gaussian covariance part, but that's less critical.

Thoughts?

**Comment by carlosggarcia** [comment]
Sounds good to me. It'd be great if computing the covariance workspace wouldn't take 1h, though. But I'd start with the easy things first.

**Comment by damonge** [comment]
and the spin-0 approximation?

**Comment by damonge** [comment]
ok, both things should alleviate that step. Also, many of the covariances should share the same cwsp

**Comment by damonge** [comment]
I'll start working on the namaster side of things. When you have time, you can do the fiducial C_ell step

**Comment by damonge** [comment]
Tests still running, but the namaster part is implemented here: https://github.com/LSSTDESC/NaMaster/pull/151

**Comment by carlosggarcia** [comment]
Benchmark with the coupled fiducial C_ell stored: 14 min vs 0.13 min (once you have it computed). 

I have also updated the times with the different approximation in the previous comment.

**Comment by carlosggarcia** [comment]
Cells and workspaces computed but not the covariance workspace. Saved fiducial coupled Cell + Toeplitz + only read MCM in the covariance workspace (used 92.7GB of RAM and 16 min in total):

- Masks read. It took 0.8215310970942179 min
- Computed C_ells. It took 3.7257207949956257 min
- Read workspaces. It took 0.008294192949930827 min
- Get covariance workspace. It took 9.694499091307323 min
- Computed Gaussian covariance. It took 1.5799858768781025 min
- Added all covariances terms. It took 6.926059722900391e-06 min
- Saved cov npz file. It took 0.006689023971557617 min 

It seems that it reduces the computation time of the covariance workspace, as well, @damonge!

**Comment by damonge** [comment]
Humm, going from 63min to 9min sounds dodgy... None of the modifications should have touched that. Is this because of toeplitz?

In any case, can we give it one lust run once everything (fiducial Cls, workspaces, covariance workspaces) has been precomputed. This is a likely scenario for most of the covariance blocks.

**Comment by carlosggarcia** [comment]
Yes, it's toeplitz. You can see it above. I'll do the run you say as well

**Comment by carlosggarcia** [comment]
@damonge see the updated comment. 4 mins with all computed except the cov_*npz file
